spring:
  application:
    name: rental-core-api

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rental_db}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8082
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: ${JWT_SECRET}
    expiry-ms: ${JWT_EXPIRY_MS:86400000}
    refresh-expiry-ms: ${JWT_REFRESH_EXPIRY_MS:604800000}
    invite-expiry-ms: ${JWT_INVITE_EXPIRY_MS:259200000}
  frontend:
    url: ${FRONTEND_URL:http://localhost:5175}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  mail:
    brevo:
      enabled: ${BREVO_ENABLED:false}
      api-key: ${BREVO_API_KEY:}
      from-email: ${BREVO_FROM_EMAIL:no-reply@rentflow.example}
      from-name: ${BREVO_FROM_NAME:RentFlow}

logging:
  level:
    com.cognix: DEBUG